#Deployment
###controllers/pb-deploy.tml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: '1Gi'
          requests:
            cpu: '1'
            memory: '1Gi'
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
